version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:5000"
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"