version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017